@startuml

title Interactive CDS Example

participant Clinician
participant CDS as "CDS Application"
participant CPG as "CPG Engine"
participant SDCManager as "SDC Form Manager"


Clinician -> CDS: Launch App with context (plandef, patient, etc)
== 1. Generate questionnaire ==

CDS -> CPG: POST /PlanDefinition/$questionnaire (url, version, data)
CPG -> CDS: Bundle<Questionnaire> pre-populated
' note left
'   See Postman
'   * "Generate Questionnaire from PlanDefinition $questionnaire"
' end note

|||

CDS -> SDCManager: POST /Questionnaire/$assemble (questionnaires from prior step)
SDCManager -> CDS: Combined Questionnaire

' note left
'   See: [[file:///Users/bkaney/projects/doudecim/CPGTraining/output/Questionnaire-QuestionnaireAssembled1.html Example Assembled]]
' end note
CDS -> Clinician: Render Questionnaire

== 2. Fill out Questionnaire ==

Clinician -> CDS: Submit (with or without changes)
break End
    CDS X<--[#8B0000]>X CPG: Cycle End
else Questionnaire Response Change
    CDS -> CDS: Build QuestionnaireResponse
end

note left
  Cycle ends when:
    * All Questionnaire items have answers; And
    * No answer changes are submitted
end note

' CDS X<--[#8B0000]>X CPG: Cycle End

' note right
'   Cycle ends when:
'     * All Questionnaire items have answers; And
'     * No answer changes are submitted
' end note

' CDS -> CDS: Build QuestionnaireResponse

' note left
'   * [[file:///Users/bkaney/projects/doudecim/CPGTraining/output/QuestionnaireResponse-QuestionnaireResponse1.html No change]]
'   * [[file:///Users/bkaney/projects/doudecim/CPGTraining/output/QuestionnaireResponse-QuestionnaireResponse2.html Specify CBC date]]
' end note

== 3. Extract Answers ==

CDS -> SDCManager: POST /QuestionnaireResponse/$extract
SDCManager -> CDS: Bundle<Case Features>

' note left
'   * [[file:///Users/bkaney/projects/doudecim/CPGTraining/output/Bundle-ExtractOutput1.html No change extract]]
'   * [[file:///Users/bkaney/projects/doudecim/CPGTraining/output/Bundle-ExtractOutput2.html Specify CBC date extract]]
' end note

== 4. Apply Guidance ==

CDS -> CPG: POST /PlanDefinition/$apply (url, version, data/case features)
CPG -> CDS: Response / CDS guidance

' note left
'   See Postman:
'   * "Call PlanDefinition $apply (without recent CBC date)"
'   * "Call PlanDefinition $apply (with recent CBC date)"
' end note

@enduml